'use strict';

const lang  = {
    lCurrent: 'Ua',

    //models/helper
    lHelpOffline: 'offline',
    lHelpYear: 'year',
    lHelpYear14: 'years',
    lHelpYearMany: 'years',
    lHelpMonth: 'month',
    lHelpMonth14: 'months',
    lHelpMonthMany: 'months',
    lHelpDay: 'day',
    lHelpDay14: 'days',
    lHelpDayMany: 'days',
    lHelpHour: 'hour',
    lHelpHour14: 'hours',
    lHelpHourMany: 'hours',
    lHelpMinute: 'minute',
    lHelpMinute14: 'minutes',
    lHelpMinuteMany: 'minutes',
    lHelpOnline: 'online',
    lHelpAgo: ' ago',
	lHelpMonths: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],

    //models/gift
    lGiftTextPart1: 'User',
    lGiftTextPart2: 'sent you a present!',

    //bot-chat-id, dating-users
    lLoadMore: 'Upload more',
    lSendBoxPlaceholder: ' Write a message...',

    //dating
    lRatingTitle: 'Rating ',
    lNextUser: 'Skip',
    lMenuProfile: 'Profile',
    lMenuFavorite: 'Favorite',
    lMenuMessage: 'Message',
    lInfoRibbon: 'My romantic story starts here!',
    lISearch: 'I search:',
    lSearchAge: 'Age:',
    lCheckGender: 'Gender:',
    lCheckMale: 'Male',
    lCheckFemale: 'Female',
    lCheckCity: 'City',
    lCheckCityChoose: '--- choose ---',
    lCheckOnlyOnline: 'Online only',
    lSearchBtn: 'Search',
    lEnterBtn: 'Enter',
    lRegisterBtn: 'Registration',
    lGiftsHeaderGifts: 'Presents',
    lGiftsHeaderMake: 'Make a present',
    lGiftsConfirmPrice: 'Х coins',
    lGiftsConfirmTitle: 'Make present?',
    lGiftsConfirmBuyBtn: 'buy',
    lGiftsConfirmCancelBtn: 'cancel',

    //fans, favorites
    lOnlineStatus: 'online',
    lAgeTitle: 'Age:',
    lAgeYears: 'Years,',
    lProfileCountry: 'Ukraine',
    lMenuChat: 'Chat',

    //footer
    lPublicNotifyMessage: 'You can send private messages as soon as you make your ' +
    'Profile is available for meetings for other users',
    lPublicNotifySettingsBtn: 'Settings',
    lPublicNotifyCancelBtn: 'Cancel',

    //sidemenu
    lSidemenuName: "Name",
    lSidemenuAge: 'Age',
    lSidemenuCity: 'City',
    lSidemenuEnter: 'Enter',
    lSidemenuNews: 'News',
    lSidemenuMessages: 'Message',
    lSidemenuMeetings: 'Meetings',
    lSidemenuFavorites: 'Favorites',
    lSidemenuFans: 'Fans',
    lSidemenuPeople: 'FAvorites',
    lSidemenuRibbon: 'Feed',
    lSidemenuMusic: 'Music',
    lSidemenuRadio: 'Radio',
    lSidemenuNotifications: 'Notifications',
    lSidemenuSettings: 'Settings',

    //header
    lHeaderTitle: 'Main',
    lHeadingAge: 'years',
    lHeadingOnline: 'online',
    lHeadingOffline: 'offline',
    lHeadingTitleFavorites: 'Favorites',
    lHeadingTitleFans: 'Favorites',
    lHeadingTitleSettings: 'Settings',
    lHeadingTitleNews: 'News',
    lHeadingTitleMessages: 'Messages',
    lHeadingTitleRadio: 'Radio',
    lHeadingTitleMySub: 'MySub',
    lHeadingTitleSubToMe: 'Fans',

    //header-admin
    lSidemenuMessagesRibbon: 'Messages feed',
    lSidemenuUsers: 'Users',
    lSidemenuBotChat: 'BotChat',

    //register-login forms
    lFormNickPlace: 'Nick...',
    lFormMailPlace: 'email...',
    lFormPassPlace: 'password...',
    lFormPassConfPlace: 'password confirm...',
    lFormRegisterBtn: 'Register',
    lFormLoginBtn: 'Enter',
    lFormLoginSoc: 'Login',

    //messages
    sendBoxPlaceholder: ' Write a message...',

    //news
    lNewsFilterHour: 'Hour',
    lNewsFilterToday: 'Today',
    lNewsFilterYesterday: 'Yesterday',
    lNewsFilterWeek: 'Week',

    //notifications
    lNotifTitle: 'Notification',
    lNotifClearBtn: 'Mark as read',
    lNotifTextStart: 'User',
    lNotifTextEnd: 'asks your contact information.',
    lNotifRequestAccept: 'Accept',
    lNotifRequestDecline: 'Decline',
    lNotifDeclineTitle: 'Choose a reason for decline',
    lNotifDeclineReason1: 'Pure English level',
    lNotifDeclineReason2: 'Not ready to share Personal information',
    lNotifDeclineReason3: 'Not long enough acquainted',

    //profile, profile-id
    lProfileEditBtn: 'Edit profile',
    lProfileDropdownInfo: 'information',
    lProfileInfoResidence: 'City',
    lProfileInfoBdate: 'Date of birth',
    lProfileInfoGender: 'Gender',
    lProfileInfoEues: 'Eye color',
    lProfileInfoHair: 'Hair color',
    lProfileInfoBodyType: 'Body type',
    lProfileInfoWeight: 'Weight',
    lProfileInfoKG: 'kg',
    lProfileInfoHeight: 'Height',
    lProfileInfoSM: 'cm',
    lProfileInfoReligion: 'Religion',
    lProfileInfoEducation: 'Education',
    lProfileInfoOccupation: 'Occupation',
    lProfileInfoSmoke: 'Smoke',
    lProfileInfoDrink: 'Drink',
    lProfileInfoHobbies: 'Hobby',
    lProfileInfoColors: 'Favorite colors',
    lProfileInfoSport: 'Sport',
    lProfileInfoAbroad: 'Being abroad',
    lProfileInfoInterests: 'Interests',
    lProfileInfoCharacter: 'Character',
    lProfileInfoMarital: 'Marital status',
    lProfileInfoChildren: 'Children',
    lProfileInfoGoal: 'Meeting goals',
    lProfileDropdownAboutMyself: 'About myself',
    lProfileDropdownAboutPartner: 'About partner',
    lProfileDropdownPhoto: 'Photo',
    lProfileDropdownFeed: 'Feed',
    lProfilePhotoMain: 'Make main',
    lProfilePhotoDeleteBtn: 'Delete',
    lProfilePhotoAddBtn: 'Add photo',
    lProfilePhotoLike: 'Like',
    lProfileVideoTitle: 'How to fill your profile (videoinstruction)',
    lProfileBlockUserOption: 'Block',
    lProfileUnBlockUserOption: 'UnBlock',
    lProfileClaimUser: 'Report',
    lProfileClaimOptionsTitle: 'What do you want to do?',
    lProfileClaimOptionsPublications: 'Report posts',
    lProfileClaimOptionsProfile: 'Report profile',
    lProfileClaimSend: 'Send',
	lProfileEdit: 'Edit',
	lProfileDelete: 'Delete',
	lProfileMakeMain: 'Make main',

    //profile-edit
    lInfoEditTitle: 'Information',
    lInfoEditProfileLink: 'To profile',
    lInfoEditStatus: 'Status',
    lInfoEditPlaceNotFilled: 'not filled...',
    lInfoEditSaveBtn: 'save',
    lInfoEditCancelBtn: 'cancel',
    lInfoEditName: "Name",
    lInfoEditSurname: 'Last name',
    lInfoEditNickname: 'Nickname',
    lInfoEditUseNickname: 'Use nickname instead of real name',
    lInfoEditOptionYes: 'Yes',
    lInfoEditOptionNo: 'No',
    lMonthJanuary: 'January',
    lMonthFebruary: 'February',
    lMonthMarch: 'March',
    lMonthApril: 'April',
    lMonthMay: 'May',
    lMonthJune: 'June',
    lMonthJuly: 'July',
    lMonthAugust: 'August',
    lMonthSeptember: 'September',
    lMonthOctober: 'October',
    lMonthNovember: 'November',
    lMonthDecember: 'December',

    //radio
    lRadioArtist: 'Artist',
    lRadioTrackName: 'track name',
    lRadioNameCopied: 'track name copied',

    //settings, settings-guest
    lSetTitleLang: 'Language',
    lSetLangUa: 'Ukrainian',
    lSetLangRu: 'Russian',
    lSetTitlePrivacy: 'Privacy',
    lSetPubProfile: 'Public profile',
    lSetShowComments: 'show my comments',
    lSetTitleDating: 'Datings',
    lSetWannaDateCond: '1. Check point "date in settings"',
    lSetWannaDateCheck: '   Date!',
    lSetChoosePhotoCond: '2. Chose profile picture',
    lSetBdateCond: '3. Set date of birth',
    lSetCityCond: '4. Set city of residence',
    lSetGenderCond: '5. Set gender',
    lSetSummaryCond: '6. When all conditions are fulfilled, Your profile will be ' +
    'available for our users.',
    lSetExitProfile: 'Exit profile',
    lSetDateVideoTitle: 'How to set up a mapping in dating (videoinstruction):',
    lSetAllowText: "Congratulations! You are displayed in dating!",
    lSetNotAllowText: "You are not displayed in dating!",

    //transactions
    lTransSN: 'S/N',
    lTransSpentOn: 'On',
    lTransPayType: 'Type',
    lTransSpentPay: 'number',
    lTransDate: 'Date',

    //subscribe
    lSubISus: 'Tracked',
    lSubToMeSub: 'Track',
    lSubActSub: 'Track',
    lSubActNotSub: 'Track',

    //music
    lMusicVideoTitle: 'How to use music store(відеоінструкція):'
};

module.exports = lang;